### ISSUE TITLE
Propose to link this repository to GitBook Badging Documentation

### ISSUE THREAD

**Issue by xiaoya-yaya** [badging/documentation#2]
The badging documentation hosting on CHAOSS GitBook account is linking to my own repository for now: https://github.com/xiaoya-Esther/badging-documenation/tree/master

I propose to synchronize the GitBook version with this repository, but only whom with administrator rights to this repo is able to perform this.

**Comment by GeorgLink** [comment]
I edited the settings in GitBook, removed the link with your repo and replaced it with this repo. I hope this works for you?

![Screen Shot 2020-08-31 at 10 52 55 AM](https://user-images.githubusercontent.com/8862021/91739897-2bb35f80-eb78-11ea-894f-97418f5853d2.png)

**Comment by xiaoya-yaya** [comment]
Yes, it does. Thanks, Georg!
