### ISSUE TITLE
Trying to get a better understanding of readme

### ISSUE THREAD

**Issue by mikeysan** [badging/documentation#4]
Hi folks,

Reading through your readme file to get an understanding of what this project is about when I came across this line:

"The reviewers will be assigned randomly to submissions via issue, should work with the review checklist."

Could someone please edit it a bit as I am not sure what the writer means?

**Comment by xiaoya-yaya** [comment]
Hi @mikeysan, thank you for pointing out!
There are indeed defects in the sentence expression, I've changed it to:

> "Reviewers will be randomly assigned according to the [reviewer list](https://github.com/badging/event-diversity-and-inclusion/blob/master/.github/reviewers.md). All assigned reviewers should work with the [review checklist.](https://github.com/badging/event-diversity-and-inclusion/blob/master/.github/checklist.md)"

Does it look better for you now?

**Comment by mikeysan** [comment]
It looks much better, @xiaoya-Esther. Thank you.
